<div class="produtos">
    <table>
        <tr>
            <th>Nome</th>
            <th>Codigo</th>
            <th>Valor</th>
            <th>Quantidade</th>
            <th>Atualizado em </th>
        </tr>
        <tr>
            <td>umo</td>
            <td>buga</td>
            <td>tedi</td>
            <td>tal</td>
            <td>loop</td>
        </tr>
        <tr>
            <td>umo</td>
            <td>buga</td>
            <td>tedi</td>
            <td>tal</td>
            <td>loop</td>
        </tr>
        <tr>
            <td>umo</td>
            <td>buga</td>
            <td>tedi</td>
            <td>tal</td>
            <td>loop</td>
        </tr>
    </table>
</div>